### ISSUE TITLE
Исполнитель в уведомлении Windows

### ISSUE THREAD

**Issue by schebotar** [vrizo/ya-music-controls#16]
Сейчас в уведомлении содержится информация об альбоме и композиции.
Логика выбора этих двух строк непонятна. Во всех плеерах, в том числе официальном плеере яндекса в уведомлении показываются название композиции и имя исполнителя.
Хотелось бы хотя бы настройку. #
![Снимок экрана 2022-01-26 105740](https://user-images.githubusercontent.com/51533848/151124618-82822934-da5a-4f1e-b12e-5ca59fae61df.jpg)

**Comment by vrizo** [comment]
@schebotar, спасибо за репорт. Вы хотите прислать ПР? Подправить нужно где-то здесь: https://github.com/vrizo/ya-music-controls/blob/master/source/background-script.js#L34-L39 . Я сам не знаю, когда доберусь, к сожалению.

**Comment by schebotar** [comment]
Это не уведомление от Firefox, а контрол Windows при изменении громкости.
В уведомлении от браузера все ок, а сюда вот так пробрасывается

**Comment by schebotar** [comment]
Заметил что исправлено.

**Comment by vrizo** [comment]
Я ничего не менял 🤷

**Comment by schebotar** [comment]
Значит баг винды был 
![image](https://user-images.githubusercontent.com/51533848/179986098-0555ef61-ad94-4014-8c50-f19aab787e38.png)
