### ISSUE TITLE
Интеграция с DBus или поддержка системных шорткатов для всех функций

### ISSUE THREAD

**Issue by stakancheck** [vrizo/ya-music-controls#17]
Хотел попробовать написать интеграцию с текущей сессией Я.Музыки в firefox. Как можно попробовать подключиться к расширению с linux?

Есть пара вариантов:
- как то интегрировать с dbus
- отлавливать системные шорткаты для всех функций (лайк, не нравится, пауза...)

Очень бы хотелось в каком-то из направлений получить решение. Или стоит не использовать это расширений в качестве связи сессии Я.Музыки с системой?

**Comment by vrizo** [comment]
Привет, @stakancheck ! Не совсем понял задачу. Почему Media Session API не подходит?

**Comment by stakancheck** [comment]
> Привет, @stakancheck ! Не совсем понял задачу. Почему Media Session API не подходит?

Спасибо за ответ, MS Api не дает возможности лайкнуть или добавить в чс треки.

Первое, что хочу сделать, это gnome extension для полноценного управления музыкой (включая лайки).

**Comment by vrizo** [comment]
> Первое, что хочу сделать, это gnome extension для полноценного управления музыкой (включая лайки)

Извиняюсь за долгий ответ. Не думаю, что существует возможность отлавливать системные комбинации. Может быть можно в MS API отправлять событие `togglemicrophone`, но использовать его для лайка. Для этого, конечно, потребуется своё собственное расширение.
