### ISSUE TITLE
Homepage of the addon is a prostitute website

### ISSUE THREAD

**Issue by Defman21** [vrizo/ya-music-controls#3]
Homepage of the add-on which can be accessed here: 
![image](https://user-images.githubusercontent.com/7100645/72437980-f4dd3480-37b4-11ea-9b5b-fd3e2873a724.png)

is a prostitute website. I guess it was yours at one time but someone bought it. Homepage on your [profile](https://addons.mozilla.org/en-US/firefox/user/12424945/) is affected too.

The website of the repo is affected as well.

**Comment by vrizo** [comment]
Hi, @Defman21 !

Thanks for your report! Sorry about this. Yes, it was my domain, but I didn’t renew it. It became too expensive :) I thought I changed the address everywhere, but I forgot about a couple of places. 

- GitHub repository — changed;
- AMO profile — changed;
- Plugin Settings — I'll change it in the next version;

Thanks a lot!

**Comment by vrizo** [comment]
Fixed in v.1.9 release! Thanks!
