### ISSUE TITLE
Toggle Dislike using System Media Controls

### ISSUE THREAD

**Issue by idashevskii** [vrizo/ya-music-controls#7]
There is no Dislike in Media Controls on keyboard. So I suggest to add an option in settings to use "Stop" key as "Dislike".
It is very helpful when you are listening something like "Daily playlist" and want to train Ya suggestions.

**Comment by vrizo** [comment]
Hi, @idashevskii !

Good idea! It sounds like an unexpected behavior to me, but I think it might be quite useful. What do you think if we disable it by default?

And, do the media control buttons work in your environment? I've tried multimedia a couple of times and it worked incorrectly (

**Comment by idashevskii** [comment]
Hi @vrizo 
> What do you think if we disable it by default?

Yep, of cause it should be disabled by default due to unexpected behavior. Probably it will be also helpful to allow user choose which Media Key use for Dislike or even Like action.

> And, do the media control buttons work in your environment?

Tested in:
- XFCE (Archlinux)
- Android 10 (extension was built as Chrome extension for Kiwi Browser)

Btw, in Android it is also very useful to control music from Bluetooth headset with media controls or directly from lock-screen.

**Comment by vrizo** [comment]
Hi, @idashevskii !

Now I understand it, media control buttons are available with Media Session API. I mean it doesn’t on Plugin Settings because Firefox doesn’t support multimedia keys yet. 

PR is welcomed )

**Comment by idashevskii** [comment]
> I mean it doesn’t on Plugin Settings

The major advantage of Media Session API is what it works as global hot key, not just when Firefox is on focus.

Also it integrates with OS. I just tested it on Windows 10:
![image](https://user-images.githubusercontent.com/2737339/104630822-5ed03880-56ac-11eb-8142-f82742eb04b4.png)


So you can control music without Firefox focusing even if you don't have multimedia hardware keys.

**Comment by vrizo** [comment]
Yes, that’s great! I’ve tested the plugin on Mac today and I enjoyed it! The global hotkeys feature is the most requested by users and it is finally implemented. I'm going to release Media Session API support tomorrow. Sorry for the delay.
